SELECT * FROM customer

---what is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM customer
GROUP BY gender

---which customers used a discount but still spent more than average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer) 

---which are the top 5 products with the highest average review rating?
SELECT item_purchased,ROUND(AVG(review_rating)::NUMERIC,2) as rating
FROM customer
GROUP BY item_purchased
ORDER BY rating DESC
LIMIT 5

---Compare the average purchase amounts between standard and express shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as avg_amount
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type

/*
do subscribed customers spend more? 
compare average spend and total revenue between subscribers and non-subscribers
*/
SELECT subscription_status,COUNT(customer_id) as total_customers,SUM(purchase_amount) as total_revenue,ROUND(AVG(purchase_amount),2) as avg_spend
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC

---which 5 products have the highest percentage of purchase with discounts applied?
SELECT item_purchased,ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

/*
---Segment customers into new, 
returning and loyal based on their total number of previous purchases,
and show the count of each segment.
*/
SELECT COUNT(CASE WHEN previous_purchases = 1 THEN 'New' END) as count_new,
	   COUNT(CASE WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning' END) as count_returning,
	   COUNT(CASE WHEN previous_purchases > 10 THEN 'loyal' END) as count_loyal
FROM customer 

WITH customer_type
AS
(SELECT customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'loyal'
	END as customer_segment
FROM customer
)
SELECT customer_segment, COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customer_segment 

---what are the top 3 most purchased products within each category?
with item_count as 
( 
SELECT category,item_purchased,COUNT(customer_id) as total_orders,
	   ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id)DESC) as item_rank
FROm customer
GROUP BY category, item_purchased)
SELECT category,item_purchased,total_orders,item_rank
FROM item_count
WHERE item_rank <=3

---are customers who are repeat buyers (more than 5 previous purchase) also likely to subscribe.
SELECT subscription_status,COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status

---what is the revenue contribution of each age group?
SELECT age_group,SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC

